### ISSUE TITLE
How do you compile the texts?

### ISSUE THREAD

**Issue by lancejpollard** [kanripo/KR-Catalog#1]
Hi there, what an excellent project.

I am looking at a file in one of the repos like here:

```
# -*- mode: mandoku-view; -*-
#+TITLE: 子夏易傳
#+DATE: 2015-08-24 21:53:12.047777
#+PROPERTY: ID KR1a0002
#+PROPERTY: BASEEDITION WYG    
#+PROPERTY: JUAN 提要
<pb:KR1a0002_WYG_000-1a>¶
欽定四庫全書　　　　　經部一¶
　子夏易𫝊　　　　　　　易𩔖¶
　　提要¶
　　　　(臣/)等謹案子夏易𫝊十一卷舊本題卜子夏撰¶
　　　　案説易之家最古者莫若是書其偽中生偽¶
　　　　至一至再而未已者亦莫若是書唐㑹要載開¶
　　　　元七年詔子夏易𫝊近無習者令儒官詳定¶
　　　　劉知㡬議曰漢志易有十三家而無子夏作𫝊¶
<pb:KR1a0002_WYG_000-1b>¶
```

In each repo, there are several files _001, _002, etc.. How do I compile this with the XML and everything? What should the final JSON look like for a "chapter" or how does that work? What does each PROPERTY mean too?

**Comment by lancejpollard** [comment]
Breaking down the structure some more, here is another example:

```

<pb:KR2a0019_WYG_000-6a>¶
　列傳第二¶
　　杜僧明　　　　　　周文育(子寳安/)¶
　　侯安都¶
　陳書卷九¶
　列傳第三¶
　　侯瑱　　　　　　　歐陽頠(子紇/)¶
　　吳明徹(裴子烈/)¶
　陳書卷十¶
<pb:KR2a0019_WYG_000-6b>¶
　列傳第四¶
　　周鐡虎　　　　　　程靈洗(子文季/)¶
　陳書卷十一¶
　列傳第五¶
　　黄法氍　　　　　　淳于量¶
　　章昭達¶
　陳書卷十二¶
　列傳第六¶
<pb:KR2a0019_WYG_000-7a>¶
```

- What do you do with the parenthesized text, what does it mean, can it be removed?
- What do you need to know about the indentation, is that important?
- Where can I find out more about the meaning of `pb:KR2a0019_WYG_000-6a` what all the parts are in that key? What parts do I need to know about?

**Comment by cwittern** [comment]
Hi, thank you for your interest in the project.  
Have you looked at the website https://www.kanripo.org ?  The texts in this repository are served from that website.  The code that serves that site is at https://github.com/mandoku/mdweb
There is also background information at http://blog.kanripo.org, you could start for example here: http://blog.kanripo.org/en1.html . The same information is also available as PDF: http://hdl.handle.net/2433/210140
If you want to use these texts for some kind of  NLP processing, you might also look at https://github.com/kr-shadow, which has the same texts in a precompiled format, which is easier to get a handle at.
The text format itself is described here: https://github.com/mandoku/mandoku/blob/master/doc/mandoku-format-en.org
The format/tools was developed as an alternative to the XML toolchains.  After 10 years of using this, I am now gradually gravitating back into the XML universe and am developing tools that will allow these texts to be integrated in a XML database.
