### ISSUE TITLE
Where are the JY texts (and others)

### ISSUE THREAD

**Issue by lancejpollard** [kanripo/KR-Catalog#3]
I see it trying to load files like this:

```
元始無量度人上品妙經 
DZJ0: [[dzjy:JY001/JY001_01.txt][JY001 元始無量度人上品妙經 ]]
```

Where do I get those files?

**Comment by cwittern** [comment]
This is an old link (left there basically for reasons internal to the project, to make them traceable to earlier versions), the easiest way to find these texts  is going by their KR number, which is KR5a0001 in this case.  If you come from the JY numbers, you can also use this link to find the corresponding files:
http://www.kanripo.org/catalog?coll=JY&label=%E9%81%93%E8%97%8F%E8%BC%AF%E8%A6%81
